site_name: TREC Change Detection Track
site_url: https://trec-changedet.github.io
remote_branch: gh-pages
plugins:
  - search
  - include-markdown
nav:
  - Home: 'index.md'
  - TREC 2026 guidelines: '2026.md'
not_in_nav: |
  includes/*
